### ISSUE TITLE
Missing query params in request url for Netlify and Cloudflare Worker

### ISSUE THREAD

**Issue by KABBOUCHI** [nuxt/nitro-demo#20] opened 2021-03-04 13:59 UTC
https://github.com/KABBOUCHI/nuxt-nitro-demo/blob/bc8fd5f0bd767598d1939eeb7e89c295a3d37596/server/api/hello.ts#L1-L13
```js
// ./server/api/hello.ts
import { useQuery } from "h3";

export default (req) => {
  return {
    message: "hi",

    request: {
      url: req.url,
      method: req.method,
      query: useQuery(req),
    },
  };
};
```

Vercel: https://nuxt-nitro-demo.vercel.app/api/hello?test1=1&test2=2
```json
{
   "message":"hi",
   "request":{
      "url":"?test1=1&test2=2",
      "method":"GET",
      "query":{
         "test1":"1",
         "test2":"2"
      }
   }
}
```

Netlify: https://nuxt-nitro-demo.netlify.app/api/hello?test1=1&test2=2
```json
{
   "message":"hi",
   "request":{
      "url":"/",
      "method":"GET",
      "query":{
         
      }
   }
}
```
url should be `event.path` + `event.queryStringParameters`
```js
// .output/server/chunks/nitro/lambda.js

async function handler(event, context) {
  const r = await localCall({
    event,
    url: event.path,
    context,
    headers: event.headers,
    method: event.httpMethod,
    query: event.queryStringParameters,
    body: event.body
  });
  return {
    statusCode: r.status,
    headers: r.headers,
    body: r.body.toString()
  };
}
```

possible solution:
```js
const { withQuery } = require('ufo')

const r = await localCall({
    event,
    url: withQuery(event.path, event.queryStringParameters),
    ....
```

Cloudflare: https://nuxt-nitro-demo.kabbouchi.workers.dev/api/hello?test1=1&test2=2
```json
{
   "message":"hi",
   "request":{
      "url":"/",
      "method":"GET",
      "query":{
         
      }
   }
}
```

**Comment by danielroe** [comment] 2021-03-04 16:03
I appreciate the report - thanks @KABBOUCHI ❤️

**Comment by manniL** [comment] 2021-03-17 14:40
Resolved upstream - will be fixed with the next release 😋

**Comment by alexcroox** [comment] 2021-04-04 18:55
@manniL just tried v0.2.1, still getting req undefined in nuxtServerInit FYI

```
export const actions = {
  nuxtServerInit({ commit }, { req }) {
    // req is undefined here
```

**Comment by manniL** [comment] 2021-04-04 19:16
> @manniL just tried `v0.2.1`, still getting req undefined in `nuxtServerInit` FYI
> 
> ```
> export const actions = {
>   nuxtServerInit({ commit }, { req }) {
>     // req is undefined here
> ```
> 
> However I am using Nuxt 2.15.4 and not nuxt-edge so apologies if that's the reason.

Having an undefined `req` object is not part of the original issue reported here. However, I've experienced a similar behavior a couple of days ago and reported the bug :) 

So - WIP again 😋 -

**Comment by alexcroox** [comment] 2021-04-04 19:29
Apologies, I reported the missing req in CF via PM a few weeks back and mistook this to be similar. I'll create a repro and create a new issue to avoid polluting this one 👍

**Comment by manniL** [comment] 2021-04-04 19:31
> Apologies, I reported the missing req in CF via PM a few weeks back and mistook this to be similar. I'll create a repro and create a new issue to avoid polluting this one 👍

Just double checked and can still repro missing `req` when using nitro, even in dev mode. Maybe squashing this bug could resolve the issue in prod too.

**Comment by KABBOUCHI** [comment] 2021-04-04 21:09
@manniL I was trying the new update but there a new issue:

Absolute path is throwing an error (full URL is working fine)

```js
$fetch('/api/quotes')
```

![image](https://user-images.githubusercontent.com/9212274/113521590-15083780-95a3-11eb-8a00-98900a0000e4.png)

this repo/demo has this error too https://nitro-demo.vercel.app/api

probably from this:
https://github.com/nuxt/nitro-demo/blob/a469eb6eaaed301b79eaa841b64e3b2588fe9f4e/pages/api.vue#L37-L39

**Comment by pi0** [comment] 2021-04-06 13:41
Thanks for report @KABBOUCHI. API error was due to a regression in h3. All should be fine in the latest releases. https://nitro-demo.vercel.app/api

**Closed by pi0** 2021-04-06 13:41 UTC
